### ISSUE TITLE
The code ignore files starting with an underscore

### ISSUE THREAD

**Issue by CrapuleJack** [excubo-ag/WebCompiler#54]
Wasted some hours trying to understand why your tool didn't work in my solution. Had to git clone your project and do some manual debug to find out line Program.cs:280. 

If you or someone needs underscored files ignored, this should be either or both a command line switch or a line in the json config file, with a default of OFF.

**Comment by stefanloerwald** [comment]
This is on purpose, because it's a common convention to mark files as partial files which do not require compilation. See https://stackoverflow.com/q/34889962

If you're unhappy about a free open source project that you're using, feel free to ask nicely and/or provide a PR to change what you think should be changed.

**Comment by CrapuleJack** [comment]
Yeah i'm sorry for my tone, I had spent some hours trying to figure this out and was a little pissed. Please accept my apologies.

I was trying to integrate this webcompiler to a .net core 6 project, and provide some scss / css to the "_Layout.cshtml" file. The layout is named with an underscore by default but is easy to rename.

In the end I just wish this was documented somewhere so I did not end up searching.. I may end up providing a pull request adding a switch to disable this default behavior, but its not the show stopper I though it was.

This is the only webcompiler (I found) which support docker .net compilation, I assume this will get more popular with time... Nice work.

**Comment by CrapuleJack** [comment]
For now your explanation is enough, I'm closing the issue.

**Comment by stefanloerwald** [comment]
No worries, I get the feeling of frustration when one is blocked by something rather trivial for hours. I'd appreciate a PR, maybe even two (adding docs and the feature).

To be honest, I started this project because I liked the original webcompiler VS extension, yet wanted something that's maintained and ultimately independent of VS. A dotnet tool seemed a sensible choice. And while I still dislike the alternative tooling (npm, I'm looking at you), I think that in a project that already uses docker, it is better to use multi-step builds for js/css/C# and combine all the assets for delivery. There are some pros and cons to be weighed (e.g. Scoped (S)CSS) of course, but speaking with the context of my own projects, I'm not the biggest fan of this tool anymore. I'm just maintaining it because I know it has quite a few users.

**Comment by CrapuleJack** [comment]
Thanks a lot for your understanding.

The way this project works (a dotnet tool) makes it pretty damn usefull for .net project with docker support. Im sure there are other tools out there which are multi-plaform / .net / docker compatible but this one is the first to pop up in searches. My guess is you can expect some traffic to get this way. 

Ill try to find some time to submit a PR or 2.

Keep up the good work.

**Comment by stefanloerwald** [comment]
Hi @CrapuleJack,

FYI: in the newest version (3.3.0-preview.1), you can modify this behavior, thanks to the work of @kaizen365.

Stefan

**Comment by CrapuleJack** [comment]
Thanks a lot for the heads-up :) keep up the good work
