### ISSUE TITLE
Error when running against .Net Core 6.0.6

### ISSUE THREAD

**Issue by ifflanb** [excubo-ag/WebCompiler#64]
I am trying to run this on an AWS Ubuntu Code Build server that has a maximum available .net version of 6.0.6.

I am getting the following error:

The framework 'Microsoft.AspNetCore.App', version '6.0.7' (x64) was not found.
--
133 | - The following frameworks were found:
134 | 6.0.6 at [/root/.dotnet/shared/Microsoft.AspNetCore.App]
135 |  
136 | You can resolve the problem by installing the specified framework and/or SDK.
137 |  
138 | The specified framework can be found at:
139 | - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=6.0.7&arch=x64&rid=ubuntu.22.04-x64
140 |  
141 | [Container] 2022/07/27 05:21:21 Command did not exit successfully dotnet run tool webcompiler -r wwroot --project ./Source/IntelligenceReporting.WebApp/IntelligenceReporting.WebApp.csproj exit status 150

**Comment by ifflanb** [comment]
Does the tool rely on 6.0.7?

**Comment by stefanloerwald** [comment]
Hi @ifflanb,

To the best of my knowledge, there's no direct dependency on a particular net6.0 version, but it might be due to one of the packages this tool depends on. You can try using a slightly older version of the tool and see whether that works. There's not much changing in the minor releases other than bringing dependencies up-to-date, so there's little risk in going back.

Hope that helps
Stefan
