### ISSUE TITLE
Version 3.X still in Preview?

### ISSUE THREAD

**Issue by travaille-dev** [excubo-ag/WebCompiler#65]
In version 3 you moved the compiler to from libsass to dartsass which supports compilation on m1 apple chips. 
In nuget the last stable version is 2.7 even though we are up to 3.3.64 in nuget. 

I was just wondering if these packages were meant to be in preview still as normal dotnet tool update excubo.webcompiler says I'm up to date.

**Comment by stefanloerwald** [comment]
Hi @travaille-dev,

Yes, it is intentional that the 3.X versions remain in preview. Dartsasshost is not yet out of preview, and depending on a preview release in a non-preview package is a no-no.

That said, I don't see a blocker against using the preview version, as it's very stable.

Hope that helps
Stefan

**Comment by travaille-dev** [comment]
Stefan,

Thanks for letting me know that Dartsasshost is still in preview. 
I can confirm that upgrading 3.3.64 works fine. There were some minor breaking changes from the 2.7 custom config, but those were well documented on the readme as well as the console output.
